updated

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -36,6 +36,10 @@ jobs:
       run: chmod +x ./gradlew
     - name: Build with Gradle Wrapper
       run: ./gradlew build
+    - name: Verify JAR exists
+      run: test -f build/libs/my-app-1.0-SNAPSHOT.jar || (echo "JAR file not found!" && exit 1)
+    - name: List Build Directory Contents
+      run: ls -l build/libs
     - name: Build and Push Docker Image
       uses: docker/build-push-action@v6
       with:
